mtg_abilities = {
    'flying': 'Can only be blocked by creatures with flying and reach.',
    'first strike': 'Deals combat damage before creatures without first strike.',
    'deathtouch': 'Any amount of damage it deals to a creature is enough to destroy it.',
    'lifelink': 'Damage dealt by the creature also causes its controller to gain that much life.',
    'hexproof': 'Cannot be the target of spells or abilities your opponents control.',
    'haste': 'Can attack and tap as soon as it comes under your control.',
    'vigilance': 'Attacking doesn’t cause the creature to tap.',
    'trample': 'Excess combat damage is dealt to the defending player or planeswalker.',
    'flash': 'Can be cast any time you could cast an instant.',
    'reach': 'Can block creatures with flying.',
    'defender': 'Cannot attack.',
    'indestructible': 'Is not destroyed by lethal damage or effects that say "destroy".',
    'menace': 'Can’t be blocked except by two or more creatures.',
    'double strike': 'Deals both first-strike and regular combat damage.',
    'protection': 'Cannot be targeted, dealt damage, or enchanted by anything of the specified quality.',
    'fear': 'Can’t be blocked except by artifact creatures and/or black creatures.',
    'intimidate': 'Can’t be blocked except by artifact creatures and/or creatures that share a color with it.',
    'shadow': 'Can block or be blocked by only creatures with shadow.',
    'islandwalk': 'Is unblockable as long as defending player controls an Island.',
    'mountainwalk': 'Is unblockable as long as defending player controls a Mountain.',
    'swampwalk': 'Is unblockable as long as defending player controls a Swamp.',
    'forestwalk': 'Is unblockable as long as defending player controls a Forest.',
    'plainswalk': 'Is unblockable as long as defending player controls a Plains.',
    'mill': 'Put the top cards from a library into a graveyard.',
    'reach': 'Can block creatures with flying.',
    'shroud': 'Can’t be the target of spells or abilities.',
    'regenerate': 'The creature can be saved from destruction under specific circumstances.',
    'exalted': 'Whenever a creature attacks alone, it gets +1/+1 until end of turn.',
    'landwalk': 'Unblockable if defending player controls a land of the specified type.',
    'annihilator': 'Whenever it attacks, defending player sacrifices a number of permanents.',
    'banding': 'Groups creatures together in combat to prevent excess damage.',
    'convoke': 'Your creatures can help cast this spell.',
    'buyback': 'You may pay an additional cost to place this spell back into your hand as it resolves.',
    'persist': 'When it dies, if it had no -1/-1 counters on it, return it to the battlefield under its owner’s control with a -1/-1 counter on it.',
    'undying': 'When it dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner’s control with a +1/+1 counter on it.',
    'undying': 'When it dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner’s control with a +1/+1 counter on it.',
    'wither': 'Deals damage to creatures in the form of -1/-1 counters.',
    'infect': 'Deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.',
    'ninjutsu': 'Allows the creature to be swapped with an unblocked attacker.',
    'horsemanship': 'Can’t be blocked except by creatures with horsemanship.',
    'soulshift': 'When this creature dies, you may return target Spirit card with a lower mana cost from your graveyard to your hand.',
    'dredge': 'You may replace any draw with putting a card from your graveyard on top of your library and milling a certain number of cards.',
    'suspend': 'Pay a smaller cost to exile a card with time counters that removes a counter in each of your upkeeps and plays it for free when the last is removed.',
    'riot': 'Enters the battlefield with your choice of a +1/+1 counter or haste.',
    'afterlife': 'When it dies, create a certain number of 1/1 white and black Spirit creature tokens with flying.',
    'cipher': 'When you cast the encoded card and it resolves, you may exile it encoded on a creature. Whenever that creature deals combat damage to a player, you may copy the encoded card and may cast the copy without paying its mana cost.',
    'haunt': 'When the creature dies, exile it haunting target creature. When the spell card is put into a graveyard after resolving, exile it haunting target creature.',
    'overload': 'You may cast the spell for its overload cost. If you do, change its text by replacing all instances of "target" with "each".',
    'splice': 'You may reveal this card from your hand as you cast a spell with the same splice subtype. If you do, copy its text box onto that spell and pay its splice cost.',
    'prowess': 'Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.',
    'escape': 'You may cast this card from your graveyard for its escape cost and exiling a number of other cards from your graveyard.',
    'rebound': 'If you cast this spell from your hand, exile it as it resolves. At the beginning of your next upkeep, you may cast this card from exile without paying its mana cost.',
    'adapt': 'If this creature has no +1/+1 counters on it, put a certain number of +1/+1 counters on it.',
    'amplify': 'As this creature enters the battlefield, put a +1/+1 counter on it for each card you reveal in your hand that shares a creature type with it.',
    'battalion': 'Whenever this creature and at least two other creatures attack, it gets a certain effect.',
    'bloodthirst': 'If an opponent was dealt damage this turn, this permanent enters the battlefield with a certain number of +1/+1 counters on it.',
    'cascade': 'When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost.',
    'champion': 'When this enters the battlefield, sacrifice it unless you exile another creature you control. When this leaves the battlefield, that card returns to the battlefield.',
    'changeling': 'This card is every creature type.',
     'changeling': 'This card is every creature type.',
    'conspire': 'As you cast this spell, you may tap two untapped creatures you control that share a color with it. When you do, copy it.',
    'cumulative upkeep': 'At the beginning of your upkeep, put an age counter on this permanent, then sacrifice it unless you pay its upkeep cost for each age counter on it.',
    'cycling': 'You may pay the cycling cost and discard this card to draw a card.',
    'dash': 'You may cast this spell for its dash cost. If you do, it gains haste, and it’s returned from the battlefield to its owner’s hand at the beginning of the next end step.',
    'delve': 'You may exile any number of cards from your graveyard as you cast this spell. It costs 1 less to cast for each card exiled this way.',
    'devour': 'As this enters the battlefield, you may sacrifice any number of creatures. This creature enters the battlefield with that many +1/+1 counters on it.',
    'embalm': 'You may pay the embalm cost and exile this card from your graveyard to create a token copy of it, except it’s white, it has no mana cost, and it’s a Zombie in addition to its other types.',
    'eternalize': 'You may pay the eternalize cost and exile this card from your graveyard to create a token copy of it, except it’s a 4/4 black Zombie.',
    'exploit': 'When this creature enters the battlefield, you may sacrifice a creature.',
    'fading': 'This permanent enters the battlefield with a certain number of fade counters on it. At the beginning of your upkeep, remove a fade counter from it. If you can’t, sacrifice it.',
    'flanking': 'Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.',
    'fuse': 'You may cast one or both halves of this card from your hand.',
    'goad': 'Until your next turn, that creature attacks each combat if able and attacks a player other than you if able.',
    'graft': 'This permanent enters the battlefield with a certain number of +1/+1 counters on it. Whenever another creature enters the battlefield, you may move a +1/+1 counter from this permanent onto it.',
    'hellbent': 'As long as you have no cards in hand, if this card is in your graveyard, effects function and triggers happen.',
    'hideaway': 'This land enters the battlefield tapped. When it does, look at the top four cards of your library, exile one face down, then put the rest on the bottom of your library.',
    'improvise': 'Your artifacts can help cast this spell. Each artifact you tap after you’re done activating mana abilities pays for 1.',
    'kicker': 'You may pay the kicker cost in addition to any other costs as you cast this spell.',
    'level up': 'Pay a cost: Put a level counter on this. Level up only as a sorcery.',
    'madness': 'If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it into your graveyard.',
    'megamorph': 'You may cast this card face down as a 2/2 creature for 3. Turn it face up any time for its megamorph cost and put a +1/+1 counter on it.'
}
